application.yml
spring:
  application:
    name: hrm-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:com/dyh/hrm/mapper/*Mapper.xml
  type-aliases-package: com.dyh.hrm.domain,com.dyh.hrm.query